### Numpy Tasks

#### Task 1

In [1]:
# 1. Create a 6x6 Numpy array with random integers between 1 and 50.

# Import all necessary pakages

import numpy as np
import matplotlib.pyplot as plt


arr = np.random.randint(1,51,(6,6))

# Display the array
print(arr)

[[50 31 46 41  4 32]
 [47 17  2 12  4 28]
 [20  8 22 30 10 19]
 [18 46 40 27  6 11]
 [39 20 18 30 21 37]
 [24 27 41 47 40 13]]


#### Task 2

In [17]:
# Extract the first two rows from Task 1.

arr_2rows = arr[(0,1),:]
print(f"First two rows:\n {arr_2rows}")


# Extract the last three columns.

arr_3cols = arr[:,(3,4,5)]
print(f"Last three columns:\n {arr_3cols}")


# Extract all even numbers

# # arr_evens = arr[(arr/2)]
# evens1 = np.array([0])
# print(arr[evens1])
# evens2 = arr[1,1] 
# print(evens2)
# evens3 = arr[2,0] , arr[2,2], arr[2,3]
# print(evens3)


even_numbers = arr[arr % 2 == 0]
print(even_numbers)

First two rows:
 [[39 44 30  8 42  6]
 [46  3  1  2 44 34]]
Last three columns:
 [[ 8 42  6]
 [ 2 44 34]
 [49 49  9]
 [47 25 48]
 [17 45  2]
 [30 49  9]]
[44 30  8 42  6 46  2 44 34 24 26  4 48 12  2 48 30]


#### Task 3

In [16]:
# Reshape the array into 3D (3,2,6) array.

reshaped_array = arr.reshape(3,2,6)
print(reshaped_array)

# Flatten the reshaped array back to 1D

flattened_array = reshaped_array.flatten()
print(flattened_array)

[[[39 44 30  8 42  6]
  [46  3  1  2 44 34]]

 [[11 24 37 49 49  9]
  [19 26  4 47 25 48]]

 [[12 31 49 17 45  2]
  [48 45 33 30 49  9]]]
[39 44 30  8 42  6 46  3  1  2 44 34 11 24 37 49 49  9 19 26  4 47 25 48
 12 31 49 17 45  2 48 45 33 30 49  9]


#### Task 4

In [14]:
# Generate a 4 x 4 identity matrix

identity_matrix = np.eye(4)
print(identity_matrix)

# Replace the diagonal with numbers from 10 to 40, with a step of 10.
diag = np.arange(10,50,10)
print(diag)

diagonal_matrix = np.diag(diag)
print(diagonal_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 20 30 40]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


#### Task 5

In [9]:
# Perform matrix multiplication
# Between 3x4 matrix of random integers (1-10) and a 4x3 matrix of random integers (1-10)

array1 = np.random.randint(1,11,(3,4))
# array1new = np.array(array1)
print(array1)
# print(array1new)

array2 = np.random.randint(1,11,(4,3))
# array2new = np.array(array2)
print(array2)
# print(array2new)
# reshaped = array2new.reshape(3,4)


# C[0][0] = (6*9 + 4 *9  )

# print(C)


# ?

arrays_multiplied = np.dot(array1 , array2)
print(f"First array * Second array:\n",arrays_multiplied)

[[ 5  1  8  4]
 [ 9 10  9  7]
 [ 3  3  4  8]]
[[1 1 7]
 [1 9 6]
 [8 6 2]
 [2 2 8]]
First array * Second array:
 [[ 78  70  89]
 [105 167 197]
 [ 54  70 111]]


#### Task 6

In [2]:
# Create a function that takes a 2D Numpy array
def transform_array(arr99):
    square_array = np.where(arr99 % 2 == 0 , arr99 ** 2, arr99 )
    odd_array = np.where(square_array % 2 != 0, -1 , square_array)
    return odd_array

test_arr = np.array([[1,2,3],
                     [4,5,6]])
transform_array(test_arr)


array([[-1,  4, -1],
       [16, -1, 36]])

In [15]:
array1d = np.random.randn(4)
print(array1d)

[ 0.08332081 -0.83152944 -0.78573223  0.25817341]
